/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/ingestion/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/jobs/{id}/quarantines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["quarantines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/sources/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/origin-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/origins/{scope}/{ingredient}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/kakao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unavailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks/{restaurantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put: operations["add"];
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogs/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogs/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ingredients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete: operations["withdraw_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/reports/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            accessToken?: string;
            tokenType?: string;
        };
        BookmarkItem: {
            address?: string;
            businessStatus?: string;
            name?: string;
            /** Format: uuid */
            restaurantId?: string;
            /** Format: date-time */
            savedAt?: string;
        };
        BookmarkPage: {
            items?: components["schemas"]["BookmarkItem"][];
            /** Format: uuid */
            nextCursor?: string;
        };
        BookmarkStatus: {
            saved?: boolean;
        };
        Bounds: {
            /** Format: double */
            east: number;
            /** Format: double */
            north: number;
            /** Format: double */
            south: number;
            /** Format: double */
            west: number;
        };
        Center: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        Claim: {
            classification?: string;
            /** Format: date-time */
            collectedAt?: string;
            components?: components["schemas"]["Component"][];
            evidenceKind?: string;
            freshness?: string;
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            lastFetchSucceededAt?: string;
            /** Format: date-time */
            observedAt?: string;
            observedPrecision?: string;
            originalExpression?: string;
            publicReference?: string;
            publicSummary?: string;
            /** Format: date-time */
            reviewedAt?: string;
            sourceName?: string;
            /** Format: date-time */
            sourceUpdatedAt?: string;
            sourceUpdatedPrecision?: string;
            /** Format: date-time */
            validFrom?: string;
            /** Format: date-time */
            validUntil?: string;
        };
        Component: {
            countryCode?: string;
            countryName?: string;
            kind?: string;
            ratio?: number;
        };
        Contact: {
            display?: string;
            number?: string;
            sourceName?: string;
        };
        CountryItem: {
            code?: string;
            name?: string;
        };
        CsrfResponse: {
            headerName?: string;
            token?: string;
        };
        Designation: {
            applicableItems?: string;
            /** Format: date */
            cancelledOn?: string;
            criteriaOriginal?: string;
            /** Format: date */
            designatedOn?: string;
            /** Format: date */
            expiresOn?: string;
            /** Format: uuid */
            id?: string;
            schemeName?: string;
            sourceName?: string;
        };
        IngestionEvent: {
            /** Format: date-time */
            createdAt?: string;
            errorCode?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            pageNo?: number;
            status?: string;
        };
        IngestionEventPage: {
            items?: components["schemas"]["IngestionEvent"][];
            /** Format: int64 */
            nextCursor?: number;
        };
        IngestionJobStatus: {
            /** Format: int64 */
            changedCount?: number;
            errorCode?: string;
            fullListingCompleted?: boolean;
            /** Format: uuid */
            id?: string;
            mode?: string;
            /** Format: date-time */
            nextAttemptAt?: string;
            /** Format: int32 */
            nextPage?: number;
            /** Format: int32 */
            pageBudget?: number;
            /** Format: int32 */
            pagesProcessed?: number;
            /** Format: int64 */
            quarantinedCount?: number;
            /** Format: int64 */
            readCount?: number;
            /** Format: date-time */
            requestedAt?: string;
            /** Format: uuid */
            sourceId?: string;
            status?: string;
            /** Format: int64 */
            totalCount?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        IngestionQuarantineItem: {
            /** Format: date-time */
            createdAt?: string;
            errorCode?: string;
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            pageNo?: number;
            /** Format: int32 */
            rowIndex?: number;
        };
        IngestionQuarantinePage: {
            items?: components["schemas"]["IngestionQuarantineItem"][];
            /** Format: uuid */
            nextCursor?: string;
        };
        IngestionRunRequest: {
            mode: string;
            /** Format: int32 */
            pageBudget: number;
            reason: string;
        };
        IngestionSourceStatus: {
            collectionAllowed?: boolean;
            credentialConfigured?: boolean;
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            intervalSeconds?: number;
            /** Format: date-time */
            lastCompletedUntil?: string;
            name?: string;
            /** Format: date-time */
            nextRunAt?: string;
            republicationAllowed?: boolean;
            scheduled?: boolean;
        };
        IngredientFilter: {
            countries?: string[];
            includeMixed?: boolean;
            /** Format: uuid */
            ingredientId?: string;
            /** @enum {string} */
            mode?: "DOMESTIC" | "COUNTRIES" | "IMPORTED_UNSPECIFIED" | "UNKNOWN";
        };
        IngredientItem: {
            category?: string;
            code?: string;
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        Item: {
            address?: string;
            businessStatus?: string;
            /** Format: double */
            distanceMeters?: number;
            /** Format: uuid */
            id?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            matchedScopes?: components["schemas"]["MatchedScope"][];
            name?: string;
        };
        MatchedScope: {
            /** Format: int32 */
            groupIndex?: number;
            /** Format: uuid */
            id?: string;
            name?: string;
            usage?: string;
        };
        MediaItem: {
            contentType?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            height?: number;
            /** Format: uuid */
            id?: string;
            /** Format: int64 */
            size?: number;
            /** Format: int32 */
            width?: number;
        };
        MemberResponse: {
            /** Format: uuid */
            id?: string;
            role?: string;
        };
        Origin: {
            claims?: components["schemas"]["Claim"][];
            /** Format: uuid */
            ingredientId?: string;
            ingredientName?: string;
            reason?: string;
            /** Format: uuid */
            selectedRecordId?: string;
            status?: string;
        };
        OriginAdminDetail: {
            corrections?: components["schemas"]["OriginCorrectionAudit"][];
            group?: components["schemas"]["OriginAdminGroup"];
            records?: components["schemas"]["OriginAdminRecord"][];
        };
        OriginAdminGroup: {
            /** Format: date-time */
            decidedAt?: string;
            /** Format: uuid */
            ingredientId?: string;
            ingredientName?: string;
            /** Format: uuid */
            restaurantId?: string;
            restaurantName?: string;
            /** Format: uuid */
            scopeId?: string;
            scopeName?: string;
            status?: string;
            usage?: string;
            /** Format: int64 */
            version?: number;
        };
        OriginAdminGroupPage: {
            items?: components["schemas"]["OriginAdminGroup"][];
            /** Format: int32 */
            nextOffset?: number;
            truncated?: boolean;
        };
        OriginAdminRecord: {
            classification?: string;
            evidenceKind?: string;
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            observedAt?: string;
            originalExpression?: string;
            /** Format: uuid */
            reportId?: string;
            /** Format: date-time */
            reviewedAt?: string;
            sourceName?: string;
            /** Format: date-time */
            sourceUpdatedAt?: string;
            /** Format: date-time */
            validUntil?: string;
            withdrawalReason?: string;
            withdrawn?: boolean;
        };
        OriginCorrectionAudit: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            id?: string;
            reason?: string;
        };
        OriginCorrectionRequest: {
            /** Format: int64 */
            expectedVersion: number;
            /** Format: uuid */
            ingredientId: string;
            reason: string;
            /** Format: uuid */
            scopeId: string;
            withdrawRecordIds: string[];
        };
        ReportClaim: {
            classification: string;
            components: components["schemas"]["ReportOriginComponent"][];
            /** Format: uuid */
            ingredientId: string;
            originalExpression: string;
        };
        ReportListItem: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            restaurantId?: string;
            restaurantName?: string;
            state?: string;
            /** Format: int64 */
            version?: number;
        };
        ReportOriginComponent: {
            countryCode?: string;
            kind: string;
            ratio?: number;
        };
        ReportPage: {
            items?: components["schemas"]["ReportListItem"][];
            /** Format: uuid */
            nextCursor?: string;
        };
        ReportReviewHistory: {
            /** Format: date-time */
            createdAt?: string;
            decision?: string;
            reason?: string;
        };
        ReportReviewRequest: {
            /** Format: uuid */
            approvedScopeId?: string;
            decision: string;
            /** Format: int64 */
            expectedVersion: number;
            privacyReviewedMediaIds: string[];
            reason: string;
        };
        ReportSubmission: {
            claims: components["schemas"]["ReportClaim"][];
            mediaIds: string[];
            /** Format: date */
            observedOn: string;
            publicationConsent?: boolean;
            /** Format: uuid */
            restaurantId: string;
            /** Format: uuid */
            scopeId?: string;
            scopeName: string;
            usage: string;
        };
        ReportUpdateRequest: {
            /** Format: int64 */
            expectedVersion: number;
            submission: components["schemas"]["ReportSubmission"];
        };
        ReportView: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            id?: string;
            reviews?: components["schemas"]["ReportReviewHistory"][];
            state?: string;
            submission?: components["schemas"]["ReportSubmission"];
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        ReportWithdrawRequest: {
            /** Format: int64 */
            expectedVersion: number;
            reason: string;
        };
        RestaurantDetail: {
            address?: string;
            /** Format: date-time */
            asOf?: string;
            businessStatus?: string;
            contact?: components["schemas"]["Contact"];
            coordinateStatus?: string;
            designations?: components["schemas"]["Designation"][];
            /** Format: uuid */
            id?: string;
            informationNotice?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            name?: string;
            scopes?: components["schemas"]["Scope"][];
        };
        Scope: {
            /** Format: uuid */
            id?: string;
            name?: string;
            origins?: components["schemas"]["Origin"][];
            precision?: string;
            usage?: string;
        };
        ScopeFilter: {
            ingredients?: components["schemas"]["IngredientFilter"][];
            /** @enum {string} */
            usage?: "SIDE_DISH" | "STEW" | "MAIN_DISH" | "OTHER" | "UNKNOWN";
        };
        SearchRequest: {
            bounds?: components["schemas"]["Bounds"];
            center?: components["schemas"]["Center"];
            cursor?: string;
            evidenceKinds?: ("SIGNBOARD_OBSERVATION" | "USER_SUBMISSION" | "SUPPLY_VERIFICATION")[];
            groups?: components["schemas"]["ScopeFilter"][];
            /** Format: int32 */
            limit?: number;
            /** Format: int32 */
            maxAgeDays?: number;
            /** Format: double */
            radiusMeters?: number;
        };
        SearchResponse: {
            /** Format: date-time */
            asOf?: string;
            items?: components["schemas"]["Item"][];
            nextCursor?: string;
            notice?: string;
            truncated?: boolean;
            zoomRequired?: boolean;
        };
        SystemStatus: {
            serviceName?: string;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngestionJobStatus"][];
                };
            };
        };
    };
    detail_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngestionJobStatus"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngestionEventPage"];
                };
            };
        };
    };
    quarantines: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngestionQuarantinePage"];
                };
            };
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngestionSourceStatus"][];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngestionJobStatus"];
                };
            };
        };
    };
    correct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OriginCorrectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OriginAdminDetail"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OriginAdminGroupPage"];
                };
            };
        };
    };
    detail_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scope: string;
                ingredient: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OriginAdminDetail"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                state?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportPage"];
                };
            };
        };
    };
    detail_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    unavailable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카카오 로그인으로 이동 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 로그인 요청 제한 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 로그인 설정 또는 의존 서비스 확인 필요 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookmarkPage"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookmarkStatus"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CountryItem"][];
                };
            };
        };
    };
    ingredients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngredientItem"][];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MediaItem"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: {
                original?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    publicImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    withdraw_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                state?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportPage"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportSubmission"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportWithdrawRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantDetail"];
                };
            };
        };
    };
    status_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
