/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/kakao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unavailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogs/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogs/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ingredients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            accessToken?: string;
            tokenType?: string;
        };
        Bounds: {
            /** Format: double */
            east: number;
            /** Format: double */
            north: number;
            /** Format: double */
            south: number;
            /** Format: double */
            west: number;
        };
        Center: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        Claim: {
            classification?: string;
            /** Format: date-time */
            collectedAt?: string;
            components?: components["schemas"]["Component"][];
            evidenceKind?: string;
            freshness?: string;
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            lastFetchSucceededAt?: string;
            /** Format: date-time */
            observedAt?: string;
            observedPrecision?: string;
            originalExpression?: string;
            publicReference?: string;
            publicSummary?: string;
            /** Format: date-time */
            reviewedAt?: string;
            sourceName?: string;
            /** Format: date-time */
            sourceUpdatedAt?: string;
            sourceUpdatedPrecision?: string;
            /** Format: date-time */
            validFrom?: string;
            /** Format: date-time */
            validUntil?: string;
        };
        Component: {
            countryCode?: string;
            countryName?: string;
            kind?: string;
            ratio?: number;
        };
        Contact: {
            display?: string;
            number?: string;
            sourceName?: string;
        };
        CountryItem: {
            code?: string;
            name?: string;
        };
        CsrfResponse: {
            headerName?: string;
            token?: string;
        };
        Designation: {
            applicableItems?: string;
            /** Format: date */
            cancelledOn?: string;
            criteriaOriginal?: string;
            /** Format: date */
            designatedOn?: string;
            /** Format: date */
            expiresOn?: string;
            /** Format: uuid */
            id?: string;
            schemeName?: string;
            sourceName?: string;
        };
        IngredientFilter: {
            countries?: string[];
            includeMixed?: boolean;
            /** Format: uuid */
            ingredientId?: string;
            /** @enum {string} */
            mode?: "DOMESTIC" | "COUNTRIES" | "IMPORTED_UNSPECIFIED" | "UNKNOWN";
        };
        IngredientItem: {
            category?: string;
            code?: string;
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        Item: {
            address?: string;
            businessStatus?: string;
            /** Format: double */
            distanceMeters?: number;
            /** Format: uuid */
            id?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            matchedScopes?: components["schemas"]["MatchedScope"][];
            name?: string;
        };
        MatchedScope: {
            /** Format: int32 */
            groupIndex?: number;
            /** Format: uuid */
            id?: string;
            name?: string;
            usage?: string;
        };
        MemberResponse: {
            /** Format: uuid */
            id?: string;
            role?: string;
        };
        Origin: {
            claims?: components["schemas"]["Claim"][];
            /** Format: uuid */
            ingredientId?: string;
            ingredientName?: string;
            reason?: string;
            /** Format: uuid */
            selectedRecordId?: string;
            status?: string;
        };
        RestaurantDetail: {
            address?: string;
            /** Format: date-time */
            asOf?: string;
            businessStatus?: string;
            contact?: components["schemas"]["Contact"];
            coordinateStatus?: string;
            designations?: components["schemas"]["Designation"][];
            /** Format: uuid */
            id?: string;
            informationNotice?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            name?: string;
            scopes?: components["schemas"]["Scope"][];
        };
        Scope: {
            /** Format: uuid */
            id?: string;
            name?: string;
            origins?: components["schemas"]["Origin"][];
            precision?: string;
            usage?: string;
        };
        ScopeFilter: {
            ingredients?: components["schemas"]["IngredientFilter"][];
            /** @enum {string} */
            usage?: "SIDE_DISH" | "STEW" | "MAIN_DISH" | "OTHER" | "UNKNOWN";
        };
        SearchRequest: {
            bounds?: components["schemas"]["Bounds"];
            center?: components["schemas"]["Center"];
            cursor?: string;
            evidenceKinds?: ("SIGNBOARD_OBSERVATION" | "USER_SUBMISSION" | "SUPPLY_VERIFICATION")[];
            groups?: components["schemas"]["ScopeFilter"][];
            /** Format: int32 */
            limit?: number;
            /** Format: int32 */
            maxAgeDays?: number;
            /** Format: double */
            radiusMeters?: number;
        };
        SearchResponse: {
            /** Format: date-time */
            asOf?: string;
            items?: components["schemas"]["Item"][];
            nextCursor?: string;
            notice?: string;
            truncated?: boolean;
            zoomRequired?: boolean;
        };
        SystemStatus: {
            serviceName?: string;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    unavailable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카카오 로그인으로 이동 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 로그인 요청 제한 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 로그인 설정 또는 의존 서비스 확인 필요 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CountryItem"][];
                };
            };
        };
    };
    ingredients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngredientItem"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantDetail"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
